#!/usr/bin/env node

/**
 * Build script to inject environment variables into web/config.js
 * This file will be loaded by index.html before Flutter runs
 * 
 * OPTIMIZED FOR NETLIFY FREE TIER:
 * - Injects all env vars at build time
 * - Eliminates need for Netlify Functions (saves function invocations)
 * - Reduces bandwidth by embedding config directly
 */

const fs = require('fs');
const path = require('path');

// Get all environment variables
const firebaseWebApiKey = process.env.FIREBASE_WEB_API_KEY || '';
const firebaseWebAppId = process.env.FIREBASE_WEB_APP_ID || '';
const firebaseMessagingSenderId = process.env.FIREBASE_MESSAGING_SENDER_ID || '';
const firebaseProjectId = process.env.FIREBASE_PROJECT_ID || '';
const cloudinaryCloudName = process.env.CLOUDINARY_CLOUD_NAME || '';
const cloudinaryPresetName = process.env.CLOUDINARY_PRESET_NAME || '';

// Validate critical variables
const hasFirebaseConfig = firebaseWebApiKey && firebaseWebAppId && firebaseProjectId;

if (!hasFirebaseConfig) {
  console.warn('⚠️ WARNING: Missing Firebase environment variables!');
  console.warn('   Make sure to set these in Netlify Dashboard:');
  console.warn('   - FIREBASE_WEB_API_KEY');
  console.warn('   - FIREBASE_WEB_APP_ID');
  console.warn('   - FIREBASE_PROJECT_ID');
  console.warn('   - FIREBASE_MESSAGING_SENDER_ID');
}

const configContent = `
// Auto-generated environment configuration for Flutter Web
// DO NOT EDIT - Generated by build-config.js at build time
// This eliminates the need for Netlify Functions (saves free tier quota)

window.__env = {
  // Firebase Configuration
  FIREBASE_WEB_API_KEY: '${firebaseWebApiKey}',
  FIREBASE_WEB_APP_ID: '${firebaseWebAppId}',
  FIREBASE_MESSAGING_SENDER_ID: '${firebaseMessagingSenderId}',
  FIREBASE_PROJECT_ID: '${firebaseProjectId}',
  
  // Cloudinary Configuration (optional)
  CLOUDINARY_CLOUD_NAME: '${cloudinaryCloudName}',
  CLOUDINARY_PRESET_NAME: '${cloudinaryPresetName}',
};

// Log configuration status (without exposing sensitive data)
console.log('📦 Environment configuration loaded:', {
  firebase: {
    projectId: window.__env.FIREBASE_PROJECT_ID || '❌ Missing',
    apiKey: window.__env.FIREBASE_WEB_API_KEY ? '✅ Set' : '❌ Missing',
    appId: window.__env.FIREBASE_WEB_APP_ID ? '✅ Set' : '❌ Missing',
    messagingSenderId: window.__env.FIREBASE_MESSAGING_SENDER_ID ? '✅ Set' : '❌ Missing',
  },
  cloudinary: {
    cloudName: window.__env.CLOUDINARY_CLOUD_NAME ? '✅ Set' : '⚠️ Not configured',
    preset: window.__env.CLOUDINARY_PRESET_NAME ? '✅ Set' : '⚠️ Not configured',
  }
});
`;

try {
  const configPath = path.join(__dirname, 'web', 'config.js');
  fs.writeFileSync(configPath, configContent, 'utf-8');
  console.log('✅ Environment configuration injected into web/config.js');
  console.log(`   Firebase: ${hasFirebaseConfig ? '✅ Configured' : '❌ Missing variables'}`);
  console.log(`   Cloudinary: ${cloudinaryCloudName ? '✅ Configured' : '⚠️ Optional - not set'}`);
} catch (error) {
  console.error('❌ CRITICAL: Could not generate web/config.js:', error.message);
  console.error('   Build may fail. Check file permissions and paths.');
  process.exit(1);
}
